<?php
$hide = '';

if (isset($item['hide']) && $item['hide'] == 'ifDefaultFolder' && $this->_currentIconFolder == 'default') {
    $hide = ' visibility:hidden ';
} 

if (isset($hidden)) {
    $hide = ' visibility:hidden ';
} 
?>

<div style="<?php echo $hide; ?>" class="festi-color-selector festi-cart-<?php echo $ident; ?>" >
    <input type="hidden" name="<?php echo $ident; ?>"  value="<?php echo $currentValue; ?>">
    <div style="background-color: <?php echo $currentValue; ?>"></div>
</div>